# Uses https://github.com/actions/add-to-project example to add PR to Anchore OSS project
name: Add pr to OSS project

on:
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add pr to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/anchore/projects/22
          github-token: ${{ secrets.GITHUB_TOKEN }}
